gigs/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('projects.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

]

projects/urls.py
from django.conf.urls import url
from . import views
from projects import views as core_views

urlpatterns = [
    url(r'^$', views.project_list, name='project_list'),
    url(r'^project_list/$', views.project_list, name='project_list'),
    url(r'^project/(?P<pk>\d+)/$', views.project_detail, name='project_detail'),
    url(r'^project/(?P<pk>\d+)/edit$', views.project_edit, name='project_edit'),
    url(r'^project_new/$', views.project_new, name='project_new'),
    url(r'^project/(?P<pk>\d+)/$', views.project_apply, name='project_apply'),
    url(r'^project/(?P<pk>\d+)/delete/$', views.project_delete, name='project_delete'),
    url(r'^project/(?P<pk>\d+)/apply/$', views.project_apply, name='project_apply'),
    url(r'^project/(?P<pk>\d+)/subscribe/$', views.project_subscribe, name='project_subscribe'),
    url(r'^accounts/profile/$', views.project_list, name='project_list'),
    url(r'^accounts/register/$', views.register, name='register'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/password/$', core_views.password, name='password'),
]

projects/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


# Create your models here.
class Project(models.Model):
    project_owner = models.ForeignKey('auth.User')
    project_title = models.CharField(max_length=50)
    project_category = models.CharField(max_length=50, default='SOME STRING')
    short_pitch = models.TextField()
    created_date = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ["-created_date"]


class Registered(models.Model):
    email = models.EmailField()
    category = models.CharField(max_length=50)

projects/forms.py
from django import forms
from .models import Project, Registered
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ('project_title', 'short_pitch', 'project_category')


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'password',
            'password2'
        )

    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']

        if commit:
            user.save()
        return user


class SubscribeForm(forms.ModelForm):
    class Meta:
        model = Registered
        fields = ('email', 'category')

    def save(self, commit=True):
        subscriber = (SubscribeForm, self).save(commit=False)
        subscriber.email = self.cleaned_data['email']
        if commit:
            subscriber.save()
        return subscriber

projects/views.py
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.views.generic import TemplateView
from .models import Project
from django.utils import timezone
from .forms import ProjectForm
from .forms import RegistrationForm
from .forms import SubscribeForm
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from social_django.models import UserSocialAuth




# Create your views here.
class HomePageView(TemplateView):
    def get(self, request):
        return render(request, 'project_list.html')


@login_required
def settings(request):
    user = request.user

    try:
        github_login = user.social_auth.get(provider='github')
    except UserSocialAuth.DoesNotExist:
        github_login = None

    try:
        twitter_login = user.social_auth.get(provider='twitter')
    except UserSocialAuth.DoesNotExist:
        twitter_login = None

    try:
        facebook_login = user.social_auth.get(provider='facebook')
    except UserSocialAuth.DoesNotExist:
        facebook_login = None

    can_disconnect = (user.social_auth.count() > 1 or user.has_usable_password())

    return render(request, 'registration/settings.html', {
        'github_login': github_login,
        'twitter_login': twitter_login,
        'facebook_login': facebook_login,
        'can_disconnect': can_disconnect
    })


@login_required
def password(request):
    if request.user.has_usable_password():
        PasswordForm = PasswordChangeForm
    else:
        PasswordForm = AdminPasswordChangeForm

    if request.method == 'POST':
        form = PasswordForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('password')
        else:
            messages.error(request, 'Please correct the error below.')
    else:
        form = PasswordForm(request.user)
    return render(request, 'registration/password.html', {'form': form})


def project_list(request):
    projects = Project.objects.all()
    query = request.GET.get("q")
    if query:
        projects = projects.filter(Q(project_title__icontains=query) |
                                   Q(short_pitch__icontains=query)
                                   ).distinct()

    page = request.GET.get('page', 1)
    paginator = Paginator(projects, 5)
    try:
        projects = paginator.page(page)
    except PageNotAnInteger:
        projects = paginator.page(1)
    except EmptyPage:
        projects = paginator.page(paginator.num_pages)
    print projects
    return render(request, 'project_list.html', {'projects': projects})


def project_detail(request, pk):
    project = get_object_or_404(Project, pk=pk)
    return render(request, 'project_detail.html', {'project': project})


def project_apply(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if project.project_owner_id == request.user.id:
        return redirect('project_list')
    if request.method == "POST":
        email = request.POST.get('email')
        if User.objects.filter(email=email).exists():
            messages.error(request, "email exists")
        form = SubscribeForm(request.POST)
        if True:
            user = User()
            user.category = request.POST.get('category')
            user.email = request.POST.get('email')
            if user.save():
                user.email = request.user
                user.save()
                messages.success(request,
                                 "Successfully subscribed.")
            return redirect('project_list')
    else:
            form = SubscribeForm()
            print messages.error(request, "Error")
    return render(request, 'project_apply.html', {'form': form})


def project_subscribe(request):
    if request.method == "POST":
        form = SubscribeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('project_list')
    else:
        form = SubscribeForm()
    return render(request, 'project_apply.html', {'form': form})


@login_required
def project_new(request):
    if request.method == "POST":
        form = ProjectForm(request.POST)
        if form.is_valid():
            project = form.save(commit=False)
            project.project_owner = request.user
            project.created_date = timezone.now()
            project.save()

            messages.success(request, 'Post added successfully')
            return redirect('project_list')

    else:
        form = ProjectForm()
        print form.errors

    return render(request, 'project_new.html', {'form': form})


@login_required
def project_edit(request, pk):
    project = get_object_or_404(Project, pk=pk)
    if project.project_owner_id != request.user.id :
        return redirect('project_list')
    if request.method == "POST":
        form = ProjectForm(request.POST, instance=project)
        print form.errors
        if form.is_valid():
            print "am valid"
            project = form.save(commit=False)
            project.project_owner = request.user
            project.created_date = timezone.now()
            project.save()
            return redirect('project_list')

    else:
        form = ProjectForm(request.POST, instance=project)
    return render(request, 'project_edit.html', {'project': project})

@login_required
def project_delete(request, pk):
    project = get_object_or_404(Project, pk=pk)
    project.delete()
    return redirect('project_list')


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm_password')
        email = request.POST.get('email')
        username = request.POST.get('username')

        if password != confirm_password:
            messages.error(request, "Passwords do not match.")
        elif User.objects.filter(email=email).exists():
            messages.error(request, "Email exists")
        elif User.objects.filter(username=username).exists():
            messages.error(request, "Username taken")
        if True:
            user = User.objects.create_user(username, email, password)
            user.username = request.POST.get('username')
            user.email = request.POST.get('email')
            if user.save():
                user.set_password(password)
            messages.success(request,
                             "Successfully registered! Login to get started.")
            return redirect('login')
    else:
        form = RegistrationForm()
        print messages.error(request, "Error")
    return render(request, 'registration/signup.html', {'form': form})

projects/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html">
   <head>
   <head>
      <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
     <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Job board and aggregator for programming jobs.Sign up today to post jobs, get job alerts, save job postings and add notes to them, and receive messages from potential employers.">

      <!-- Twitter tags -->
      <meta property="twitter:card" content="summary">
      <meta property="twitter:site" content="@remotepython">
      <title>Find remote Python jobs and developers. | RemotePython.com</title>
      <link rel="stylesheet" href="{% static 'css/styles.css' %}" type="text/css">
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
       <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link href="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">

   </head>
   <body style="">
      <!-- wrapper page -->
         <!-- wrapper page -->
      <div class="container-fluid padding">
         <!-- main-header -->
         <header class="main-header">
            <!-- main navbar -->
            <nav class="navbar main-navbar hidden-sm hidden-xs">
               <div class="container">
                  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                     <ul class="nav links navbar-nav">
                        <li><a href="{% url 'project_list' %}">Find Jobs </a> </li>
                        <li><a href="{% url 'project_new' %}">Post Project</a></li>
                        <li><a href="{% url 'register' %}">Get Alerts</a> </li>
                     </ul>
                     <ul class="nav links navbar-nav navbar-right">
                         {% if user.is_authenticated %}
                          <li><a href="{% url 'logout' %}">Logout</a> </li>
                         {% else %}
                        <li><a href="{% url 'login' %}">Login</a> </li>
                         {% endif %}
                        <li><a href="{% url 'register' %}">Sign up</a>
                    </li>
                     </ul>
                  </div>
               </div>
            </nav>
            <!-- end main navbar -->
             <!-- mobile nav-bar -->
             <div class="container">
                <nav class="mobile-nav hidden-md hidden-lg">
                    <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="#" class="navbar-brand">SIdegigs</a>

                <div class="mobile-nav-block">

                <div class="collapse navbar-collapse navBarCollapse">
                <ul class="nav navbar-nav collapse ">
                    <li><a href="{% url 'project_list' %}"><button class="btn btn-default">Find Jobs</button> </a> </li>
                    <li><a href="{% url 'project_new' %}"><button class="btn btn-default">Post Project</button></a></li>
                    <li><a href="{% url 'register' %}"><button class="btn btn-default">Get Alerts</button></a> </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{% url 'login' %}"><button class="btn btn-default">Login</button></a> </li>
                    <li><a href="{% url 'register' %}"><button class="btn btn-default">Sign up</button></a></li>
                </ul>
                </div>
                </nav>
             </div>


<div class="container">
  <div class="white-space-50"></div>
  <h3 class="text-center1">Sidegigs</h3>
    <div class="white-space-50"></div>
</div>


      </header><!-- end main-header -->
    {% block content %}
         <div class="white-space-100"></div>
    {% endblock %}


      <!-- end wrapper page -->

   </body>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-98864276-1', 'auto');
  ga('send', 'pageview');

</script>
</html>

projects/templates/index.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="tessie" content="">
	<title>Site</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link href="static/css/styles.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  < script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script>
  	    $(document).ready(function() {
  		    $('myCarousel').mycarousel({
  			    interval: 5000 * 10
  		    });
  	    })
     </script>
</head>

<body>
<!-- Navigation -->
    <div class="navbar navbar-inverse navbar-fixed-top nav">
    	<div class="container">
    		<a href="#" class="navbar-brand"><h3>Side Projects</h3></a>
    		<button class="navbar-toggle" data-toggle = "collapse" data-target = ".navHeaderCollapse">
    			<span class="icon-bar"></span>
    			<span class="icon-bar"></span>
    			<span class="icon-bar"></span>
    		</button>
    		<div class="collapse navbar-collapse navHeaderCollapse">
    			<ul class="nav navbar-nav navbar-right">
    				<li><a href="#about"><h3>About</h3></a></li>
    				<li><a href="#portfolio"><h3>Portfolio</h3></a></li>
                    <li><a href="#contact"><h3>Contact</h3></a></li>

    			</ul>
    		</div>
    	</div>
    </div>
<!-- Carousel -->
<div class="container-fluid header">
    <div id="myCarousel" class="carousel slide" data-interval=" 50000">
    	<ol class="carousel-indicators">
    		<li data-target = "#myCarousel" data-slide-to = "0" class="active"></li>
    		<li data-target = "#myCarousel" data-slide-to = "1"></li>
    		<li data-target = "#myCarousel" data-slide-to = "2 "></li>
    	</ol>
    	<div class="carousel-inner container-fluid">
    		<div class="item active">
    			<img src="static/img/one.jpg" alt="" class="img-responsive">
    			<div class="carousel-caption"><h2>Side project, ideas or hacks?</h2>
                    <a href="{% url 'register' %}"><button class="btn btn-primary btn-lg">Create account</button></a>
                    <a href="{% url 'project_new' %}"><button class="btn btn-primary btn-lg">Post Project</button></a>
                </div>
    		</div>
    		<div class="item">
    			<img src="static/img/three.jpg" alt="" class="img-responsive">
    			<div class="carousel-caption"><h2>Side project, ideas or hacks?</h2>
                    <a href="{% url 'register' %}"><button class="btn btn-primary btn-lg">Create account</button></a>
                    <a href="{% url 'project_new' %}"><button class="btn btn-primary btn-lg">Post Project</button></a>
                </div>
    		</div>
    		<div class="item">
    			<img src="static/img/five.jpg" alt="" class="img-responsive">
    			<div class="carousel-caption"><h2>Side project, ideas or hacks?</h2>
                    <a href="{% url 'register' %}"><button class="btn btn-primary btn-lg">Create account</button></a>
                    <a href="{% url 'project_new' %}"><button class="btn btn-primary btn-lg">Post Project</button></a>
                </div>
    		</div>

    	</div>
    	<a class="carousel-control left" href="#myCarousel" data-slide = "prev">
    		<span class="icon-prev"></span>
    	</a>
    	<a class="carousel-control right" href="#myCarousel" data-slide = "next">
    		<span class="icon-next"></span>
    	</a>
    </div>
    <!-- carousel -->
    <!-- modal -->
      <div id="MyModal" class="modal fade" role="dialog">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
               <button type="button" class="close" data-dismiss="modal">&times;</button>
               <h4 class="modal-title">Sign up</h4>
            </div>
            <div class="modal-body">
              <form method="post" id="registration_form"></form>
                <div class="form-group">
                  <label for="inputUsername">Username</label>
                    <input type="username" class="form-control" id="form_username">
                </div>
                <div class="form-group">
                  <label for="inputPassword">Password</label>
                  <input type="password" class="form-control" id="form_password">
                </div>
                <div class="form-group">
                  <label for="inputPassword">Confirm Password</label>
                  <input type="password" class="form-control" id="form_retype_password">
                </div>
                <div class="form-group">
                  <label for="inputEmail">Email</label>
                  <input type="email" class="form-control" id="form_email">
                </div>
                <label><input type="checkbox"> Remember me</label>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Submit</button>
            </div>
          </div>
        </div>
      </div>
    <div class="row">
    	<div class="col-md-12 text">
    		<h2 id="about">About us</h2>
            <p class="text-center">We are a market place for projects. Bringing together project owners and developers </p>
    	</div>
    </div>
    </div>
    <br>

<!-- About -->
	<div class="container-fluid">
		<div class="row">
			<div class="col-md-6">
                <div class="column1">
                <h2 class="text-center">Post project</h2>
				<p class="text">A site for side projects, hacks and ideas. List a project that you want to sell and have people bid for the project</p>
                </div>
			</div>
			<div class="col-md-6">
                 <div class="column2">
                 <h2 class="text-center">Bid project</h2>
				<p class="text"> Are you looking to earn money or be part of a project? Bid to be part of the listed projects and earn money while at it</p>
                </div>
			</div>
		</div>
	</div>
    <br><br>

<!-- Parallax -->
	<section class="parallax">
		<div class="parallax"></div>

			<div class="row text-center">
				<p class="text" id="portfolio">What we do</p>
                <div class="row position">
                <div class="col-md-4">
                    <h4 class="text">Offer a central location for<br> identifying right side project ideas<br> and start building – In the quickest time.</h4   >
                </div>
				<div class="col-md-4">
					<h4 class="text">Offer a central location for<br> identifying right side Project Ideas<br> and start building – In the quickest time.</h4>
				</div>
                <div class="col-md-4">
                   <h4 class="text">Offer a central location for<br> identifying right side Project Ideas<br> and start building – In the quickest time.</h4>
                </div>
                </div>
			</div>
	</section>
    <br><br><br>

    <div class="container-fluid footer">
    <div class="row">
        <div class="row">
            <div class="col-lg-4 text-center">
                <h3>Side Projects</h3>
                <h4 class="text-center">Sell, buy and discover side projects</h4>

            </div>
            <div class="col-lg-4 text-center">

                 <h3>Resources</h3>
                 <h4 class="text-center">Blog</h4>
                 <h4 class="text-center ">Pricing</h4>
            </div>
            <div class="col-lg-4 text-center" id="contact">
                 <h3>Get social</h3>
                    <ul class="list-inline">
                        <li>
                            <a href="https://twitter.com/Tessie_Waithira" target="_blank"> <i class="fa fa-twitter social"></i></a>
                        </li>
                        <li>
                            <a href="https://web.facebook.com/tessie.waithira" target="_blank"> <i class="fa fa-facebook social"></i></a>
                        </li>
                         <li>
                            <a href="https://github.com/TessieWaithira" target="_blank"> <i class="fa fa-github social"></i></a>
                        </li>
                    </ul>
            </div>
        </div>
    </div>
    <hr>
    <div class="col-md-12 text-center">
        <h4>© 2017 Side projects . All rights reserved </h4>
    </div>
    </div>
</body>
</html>

projects/templates/project_apply.html
{% extends 'base.html' %}
{% block content %}
      <!-- body-content -->
  <div class="container">
      <br><br>
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
          <h2 class="text-center">
      Interested in this job?
        </h2>
      <p class="text-center">Enter your email and we will get back to you</p>
        <form method="POST" class="post-form">
         {% csrf_token %}
          <div class="form-group">
            <label for="id_email">Email*</label>
            <input id="id_email" type="text" name="email" value="" class="form-control" >
            <p class="text-center">Enter a category you want to receive job alerts on</p>
            <label for="id_category">Category*</label>
              <select name="category" class="form-control">
                  <option value="android">Android</option>
                  <option value="web">Web</option>
                  <option value="ui/ux">UI/UX</option>
              </select>
          </div>
          <div class="form-group text-center">
              <a href="{% url 'project_list'%}"><button class="btn btn-lg btn-primary">Subscribe </button></a>
          </div>
        </form>
      </div>
    </div>
  </div>
<!--end body-content -->
{% endblock %}

projects/templates/project_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="size text-center">
    <br>
       <h1 class="text-center">{{ project.project_title|upper }}</h1>
     <p>{{ project.short_pitch|linebreaksbr }}</p>
        {% if user.is_authenticated and user.id == project.project_owner_id %}
        <div class="text-center">
             <a href="{% url 'project_edit' pk=project.pk %}"><button class="btn btn-primary btn-lg">Edit</button></a>
        <a href="{% url 'project_delete' pk=project.pk %}"><button class="btn btn-lg btn-danger">Delete</button></a>
         {% else %}
             <a href="{% url 'project_apply' pk=project.pk %}"><button class="btn btn-lg btn-primary">Apply </button></a>
        {% endif %}


    <br><br><br>
     <div class="white-space-100"></div>
        </div>
</div>
</div>

{% endblock %}

projects/templates/project_edit.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
<div class="row text-center">
     <form method="POST" class="post-form">
        {% csrf_token %}
       {% if project.project_owner %}
            <p><label for="id_project_title">Project title:</label> <input id="id_project_title" maxlength="50" name="project_title" type="text" class="form-control" value="{{ project.project_title }}" required /></p>
         <div class="form-group">
              <p>Projects Category*</p>
           <select name="project_category" class="form-control" value="{{ project.project_category }}">
               <option value="Android">Android</option>
               <option value="CMS">CMS</option>
           </select>
         </div>
        <p><label for="id_short_pitch">Short pitch:</label> <textarea cols="40" id="id_short_pitch" name="short_pitch" rows="10" class="form-control" required>
        {{ project.short_pitch }}
        </textarea></p>
        <a href="{% url 'project_list' %}" ><button type="submit" class="save btn btn-primary btn-lg">Save</button></a>
       {% endif %}
     </form>
</div>
</div>
  <div class="white-space-50"></div>
{% endblock %}

projects/templates/project_new.html
<div xmlns="http://www.w3.org/1999/html">
{% extends 'base.html' %}
{% block content %}
    </div>
    <div class="container">
        <div class="row text-center">
          <form method="POST" class="post-form" action="">
            {% csrf_token %}
          <div class="form-group">
              <p>Project Title*</p>
            <input id="id_project_title" type="text" name="project_title"  class="form-control" placeholder="Example: Android/Web app">
          </div>
               <div class="form-group">
              <p>Projects Category*</p>
           <select name="project_category" class="form-control">
               <option value="Android">Android</option>
               <option value="CMS">CMS</option>
           </select>
               </div>
          <div class="form-group">
              <p>Short Description*</p>
            <textarea cols="2" id="id_short_pitch" class="form-control" name="short_pitch" value="{{ project.short_pitch }}" rows="10"> </textarea></p>
          </div>


          <div class="form-group">
              <a href="{% url 'project_list' %}"><button type="submit" class="btn btn-primary btn-lg">Submit</button></a>
          </div>
        </form>
        </div>
    </div>
       <div class="white-space-50"></div

{% endblock %}
</div>